export const queryKeys = {
  auth: { me: ['auth', 'me'] },
  projects: (filters) => ['projects', filters],
  project: (id) => ['project', id],
  projectMembers: (id) => ['project', id, 'members'],
  projectLinks: (id) => ['project', id, 'links'],
  projectPhases: (id) => ['project', id, 'phases'],
  projectMilestones: (id) => ['project', id, 'milestones'],
  projectAllocations: (id) => ['project', id, 'allocations'],
  projectRisks: (id) => ['project', id, 'risks'],
  projectIssues: (id) => ['project', id, 'issues'],
  projectFinancialSummary: (id) => ['project', id, 'financialSummary'],
  projectBudgetLines: (id) => ['project', id, 'budgetLines'],
  projectSpendRecords: (id) => ['project', id, 'spendRecords'],
  tasks: (filters) => ['tasks', filters],
  task: (id) => ['task', id],
  taskActivity: (id) => ['task', id, 'activity'],
  users: (filters) => ['users', filters],
  user: (id) => ['user', id],
  invitations: ['invitations'],
  dashboardOverview: ['dashboard', 'overview'],
  dashboardAttention: ['dashboard', 'attention'],
  vaultEntries: (filters) => ['vaultEntries', filters],
  vaultEntry: (id) => ['vaultEntry', id],
  vaultFiles: (entryId) => ['vaultFiles', entryId],
  workload: ['resources', 'workload'],
  assets: ['assets'],
  memberAllocations: (filters) => ['memberAllocations', filters],
  assetAllocations: (filters) => ['assetAllocations', filters],
};
