import type { ProjectFilters } from '../types/api.js';

export const queryKeys = {
  auth: { me: ['auth', 'me'] as const },
  projects: (filters?: ProjectFilters) => ['projects', filters] as const,
  project: (id: number) => ['project', id] as const,
  projectMembers: (id: number) => ['project', id, 'members'] as const,
  projectLinks: (id: number) => ['project', id, 'links'] as const,
  projectPhases: (id: number) => ['project', id, 'phases'] as const,
  projectMilestones: (id: number) => ['project', id, 'milestones'] as const,
  milestone: (id: number) => ['milestone', id] as const,
  projectAllocations: (id: number) => ['project', id, 'allocations'] as const,
  projectRisks: (id: number) => ['project', id, 'risks'] as const,
  projectIssues: (id: number) => ['project', id, 'issues'] as const,
  projectFinancialSummary: (id: number) => ['project', id, 'financialSummary'] as const,
  projectBudgetLines: (id: number) => ['project', id, 'budgetLines'] as const,
  projectSpendRecords: (id: number) => ['project', id, 'spendRecords'] as const,
  tasks: (filters?: Record<string, unknown>) => ['tasks', filters] as const,
  task: (id: number) => ['task', id] as const,
  taskActivity: (id: number) => ['task', id, 'activity'] as const,
  users: (filters?: Record<string, unknown>) => ['users', filters] as const,
  user: (id: number) => ['user', id] as const,
  memberSummary: (id: number) => ['memberSummary', id] as const,
  invitations: ['invitations'] as const,
  dashboardOverview: ['dashboard', 'overview'] as const,
  dashboardAttention: ['dashboard', 'attention'] as const,
  vaultEntries: (filters?: Record<string, unknown>) => ['vaultEntries', filters] as const,
  vaultEntry: (id: number) => ['vaultEntry', id] as const,
  vaultFiles: (entryId: number) => ['vaultFiles', entryId] as const,
  workload: ['resources', 'workload'] as const,
  assets: ['assets'] as const,
  memberAllocations: (filters?: Record<string, unknown>) => ['memberAllocations', filters] as const,
  assetAllocations: (filters?: Record<string, unknown>) => ['assetAllocations', filters] as const,
};
