import type { ProjectFilters } from '../types/api.js';

export const queryKeys = {
  auth: { me: ['auth', 'me'] as const },
  projects: (filters?: ProjectFilters) => ['projects', filters] as const,
  project: (id: string) => ['project', id] as const,
  projectMembers: (id: string) => ['project', id, 'members'] as const,
  projectLinks: (id: string) => ['project', id, 'links'] as const,
  projectPhases: (id: string) => ['project', id, 'phases'] as const,
  projectMilestones: (id: string) => ['project', id, 'milestones'] as const,
  milestone: (id: string) => ['milestone', id] as const,
  projectAllocations: (id: string) => ['project', id, 'allocations'] as const,
  projectWorkload: (id: string, dateRange?: { starts_on?: string; ends_on?: string }) => ['project', id, 'workload', dateRange] as const,
  projectRisks: (id: string) => ['project', id, 'risks'] as const,
  projectIssues: (id: string) => ['project', id, 'issues'] as const,
  allRisks: ['allRisks'] as const,
  allIssues: ['allIssues'] as const,
  projectFinancialSummary: (id: string) => ['project', id, 'financialSummary'] as const,
  projectBudgetLines: (id: string) => ['project', id, 'budgetLines'] as const,
  projectSpendRecords: (id: string) => ['project', id, 'spendRecords'] as const,
  tasks: (filters?: Record<string, unknown>) => ['tasks', filters] as const,
  task: (id: string) => ['task', id] as const,
  taskActivity: (id: string) => ['task', id, 'activity'] as const,
  users: (filters?: Record<string, unknown>) => ['users', filters] as const,
  user: (id: string) => ['user', id] as const,
  memberSummary: (id: string) => ['memberSummary', id] as const,
  invitations: ['invitations'] as const,
  dashboardOverview: ['dashboard', 'overview'] as const,
  dashboardAttention: ['dashboard', 'attention'] as const,
  vaultEntries: (filters?: Record<string, unknown>) => ['vaultEntries', filters] as const,
  vaultEntry: (id: string) => ['vaultEntry', id] as const,
  vaultFiles: (entryId: string) => ['vaultFiles', entryId] as const,
  workload: (dateRange?: { starts_on?: string; ends_on?: string }) => ['resources', 'workload', dateRange] as const,
  capacityProfiles: (userId: string) => ['users', userId, 'capacityProfiles'] as const,
  allCapacityProfiles: ['resources', 'capacityProfiles'] as const,
  allAvailability: ['resources', 'availability'] as const,
  memberAllocations: (filters?: Record<string, unknown>) => ['memberAllocations', filters] as const,
};
